<a href="https://colab.research.google.com/github/Amaansaifidev/Learning-python-for-ai-ml/blob/master/numpy-in-python/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(12)

In [ ]:
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr2 = np.zeros((3,4))

In [ ]:
arr3 = np.ones((3,4))

In [ ]:

mask = arr > 5

arr[mask]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
Newarr = np.where((arr > 3) )

In [ ]:
print(arr[Newarr])

[ 4  5  6  7  8  9 10 11]


In [ ]:
filtered = arr[(arr >= 0) & (arr <= 7)]

In [ ]:
filtered

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:

arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])

combined = np.concatenate((arr3, arr4))
print(combined)

[1 2 3 4 5 6]


In [ ]:
arr5 = np.arange(12).reshape((3,4))

In [ ]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr5 = arr5 * 2

In [ ]:
arr5

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
arr5 = np.vstack((arr5, [24, 26, 28, 30]))

In [ ]:
arr6 = arr5[:, 1:]

In [ ]:
arr6.sum(axis = 1)

array([12, 36, 60, 84])

In [ ]:
arr6

array([[ 2,  4,  6],
       [10, 12, 14],
       [18, 20, 22],
       [26, 28, 30]])