<a href="https://colab.research.google.com/github/Amaansaifidev/Learning-python-for-ai-ml/blob/master/numpy-in-python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.arange(12)

In [4]:
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr2 = np.zeros((3,4))

In [6]:
arr3 = np.ones((3,4))

In [7]:

mask = arr > 5

arr[mask]

array([ 6,  7,  8,  9, 10, 11])

In [9]:
Newarr = np.where((arr > 3) )

In [10]:
print(arr[Newarr])

[ 4  5  6  7  8  9 10 11]


In [11]:
filtered = arr[(arr >= 0) & (arr <= 7)]

In [12]:
filtered

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:

arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])

combined = np.concatenate((arr3, arr4))
print(combined)

[1 2 3 4 5 6]


In [15]:
arr5 = np.arange(12).reshape((3,4))

In [16]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr5 = arr5 * 2

In [18]:
arr5

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [19]:
arr5 = np.vstack((arr5, [24, 26, 28, 30]))

In [20]:
arr6 = arr5[:, 1:]

In [21]:
arr6.sum(axis = 1)

array([12, 36, 60, 84])

In [22]:
arr6

array([[ 2,  4,  6],
       [10, 12, 14],
       [18, 20, 22],
       [26, 28, 30]])

In [24]:
arr6.sum(axis = 0)

array([56, 64, 72])