<a href="https://colab.research.google.com/github/Amaansaifidev/Learning-python-for-ai-ml/blob/master/Numpy-in-python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.arange(12)

In [4]:
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr2 = np.zeros((3,4))

In [6]:
arr3 = np.ones((3,4))

In [7]:

mask = arr > 5

arr[mask]

array([ 6,  7,  8,  9, 10, 11])

In [20]:
Newarr = np.where((arr > 3) )

In [22]:
print(arr[Newarr])

[ 4  5  6  7  8  9 10 11]


In [17]:
filtered = arr[(arr >= 0) & (arr <= 7)]

In [19]:
filtered

array([0, 1, 2, 3, 4, 5, 6, 7])